language: ruby

rvm: 2.6.5

branches:
  only:
    - master
    - travis

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - bin/setup
  - bundle exec rspec
  - bin/startup
